<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>lol</string>
	</array>
	<key>name</key>
	<string>LOLCODE</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>\b(\W|^)(HAI|R|AN|TIL|MAEK|LOOP|KTHXBAI|I\sFOUND|IM\sIN|IM\sOUTTA|MKAY|LOL|GTFO)(\W|$)\b</string>
			<key>name</key>
			<string>keyword.lol</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\W|^)SUMZ\sOF|SUM\sOF|DIFF\sOF|DIFFZ\sOF|QUOSHUNT\sOF|QUOSHUNTZ\sOF|PRODUKTZ\sOF|PRODUKT\sOF|MODZ\sOF|MOD\sOF|BIGGR\sOF|SMALLR\sOF</string>
			<key>name</key>
			<string>support.function.LOLCODE.lol</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\W|^)BOTH\sOF|EITHER\sOF|WON\sOF|NOT|ALL\sOF|ANY\sOF</string>
			<key>name</key>
			<string>support.function.LOLCODE.lol</string>
		</dict>
		<dict>
			<key>match</key>
			<string>BOTH\sSAEM|DIFFRINT</string>
			<key>name</key>
			<string>support.function.LOLCODE.lol</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\s(\W|^)UP|UPPIN|YR</string>
			<key>name</key>
			<string>support.function.LOLCODE.lol</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\W|^)COMPLAIN|VISIBLE|GIMMEH</string>
			<key>name</key>
			<string>support.function.LOLCODE.lol</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\W|^)TROOF|YARN|NOOB|NUMBAR|NUMBR</string>
			<key>name</key>
			<string>storage.type.lol</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\W|^)WIN|FAIL</string>
			<key>name</key>
			<string>keyword.lol</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\W|^)OIC|OMG|OMGWTF|MEBBE|WTF\?</string>
			<key>name</key>
			<string>string.quoted.other.lt-gt.include.lol</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\s*\s*CAN\sHAZ\b\s+</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.import.include.lol</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\?</string>
			<key>name</key>
			<string>string.quoted.other.include.lol</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\s*\s*ITZ\s*((ALL|A)*)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.import.include.lol</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\n</string>
			<key>name</key>
			<string>string.quoted.other.include.lol</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\s*\s*IN\sMAH</string>
			<key>name</key>
			<string>keyword.lol</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\s*HOW\sDUZ\sI</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>meta.keyword.include.lol</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\s</string>
			<key>name</key>
			<string>support.function.STL.lol</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\s*\s*I\sHAS\sA\b\s+</string>
			<key>name</key>
			<string>string.quoted.other.lt-gt.include.lol</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\s*\s*O\sRLY\?</string>
			<key>name</key>
			<string>string.quoted.other.lt-gt.include.lol</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\s*\s*YA\sRLY</string>
			<key>name</key>
			<string>string.quoted.other.lt-gt.include.lol</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\s*\s*NO\sWAI</string>
			<key>name</key>
			<string>string.quoted.other.lt-gt.include.lol</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\s*IF\sU\sSAY\sSO</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>meta.keyword.include.lol</string>
				</dict>
			</dict>
			<key>end</key>
			<string>$\n?</string>
			<key>name</key>
			<string>support.function.STL.lol</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.lol</string>
				</dict>
			</dict>
			<key>end</key>
			<string>"</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.lol</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double.lol</string>
		</dict>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>meta.toc-list.banner.block.lol</string>
						</dict>
					</dict>
					<key>match</key>
					<string>BTW</string>
					<key>name</key>
					<string>comment.block.lol</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>OBTW</string>
					<key>end</key>
					<string>TLDR</string>
					<key>name</key>
					<string>comment.block.lol</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>OBTW</string>
					<key>end</key>
					<string>TLDR.*\n</string>
					<key>name</key>
					<string>invalid.illegal.stray-comment-end.lol</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.lol</string>
	<key>uuid</key>
	<string>f2bee1bd-e059-41c0-858e-bf17c1340814</string>
</dict>
</plist>
